### ISSUE TITLE
create a web site

### ISSUE THREAD

**Issue by monkeypants** [pocketmoneyindustries/gledden-st-eggs#1]
we have set up https://chookamatronics.githubpages.io/gledden-st-eggs

it needs to say the right things on it:
 * some info about gledden st eggs (pocket money venture)
 * some info about the chooks (including pictures etc)
 * how it works (we have spare eggs, and deliver them to other people in Gledden st if they want to buy them)

Pictures:
 * of the chickens getting fed
 * laying eggs
 * outside running arround.
 * spare egg pile (lots of eggs)
 * a picture of the Gledden st sign.

It needs to link to the sign up web page (and the unsubscribe page).

**Comment by monkeypants** [comment]
note, the PR #8 updated the page

**Comment by yaya-galah** [comment]
Maybe PocketMoneyEggs.com would be a better address?

**Comment by yaya-galah** [comment]
I think that Holly had a very exciting day today,  I also think that we should try do the same thing with Lucky since she is a lighter color...

**Comment by monkeypants** [comment]
We can do more pictures later, and we need to make a link to the sign-up page (when it exists, re #2). But I think this is done.
