### ISSUE TITLE
fix typo "Apocket"

### ISSUE THREAD

**Issue by monkeypants** [pocketmoneyindustries/gledden-st-eggs#12]
fix typo on the `/README.md` (not the one in `/docs/`).

It says  `Apocket money industry, a modern urban flock.`

There should be a gap between "A" and "pocket". And maybe it should say something else too? what is this for, what's the story? maybe this page should link to the exciting weekend picture of you climbing the street pole to put the chicken up there?

**Comment by monkeypants** [comment]
this is the "Apocket ticket", it's better to comment about this here rather than in  #6 - there's an important art to staying on topic :)

**Comment by yaya-galah** [comment]
ok

**Comment by monkeypants** [comment]
let me show you how to make a local "working copy" of the repository, so you can edit the file on your computer, then do `git add`, and then `git commit` and `git push`.

**Comment by monkeypants** [comment]
* [x] find your local copy of the repo (using `pwd` and `ls` and `cd` commands).
 * [x] do a `git pull` to make sure it is up to date
 * [x] edit the file `README.md` and fix the typo, save changes
 * [x] use `git add README.md` command to start forming the commit (this commit has only one file, so only need to do one of these).
 * [x] use `git commit -m "fix typo in README"` to make the commit with a useful comment (the stuff in quotes after the `-m`). Useful describe change in this commit, and tell the system what to do to make it.
 * [x] use `git push` command to push the changes from your machine to GitHub

after that, robots will take care of the rest
