### ISSUE TITLE
collect images for flyers

### ISSUE THREAD

**Issue by monkeypants** [pocketmoneyindustries/gledden-st-eggs#18]
before we do #5 we need a picture of a chicken on every letterbox in the street:

 * [x] No 1
 * [x] No 2
 * [x] No 3
 * [x] No 4
 * [x] No 5
 * [x] No 6
 * [x] No 7
 * (No 8)
 * [x] No 9
 * (No 10)
 * [x] No 11
 * [x] No 12
 * [x] No 13
 * [x] No 14
 * [x] No 15
 * [x] No 16
 * (No 17)
 * [x] No 18
 *  (No 19)
 * [x] No 20
 * (No 21)
 * [x] No 22
 * (No 23)
 * [x] No 24
 * (No 25)
 * [x] No 26
 * [x] No 27
 * [x] No 28
 * [x] No 29
 * [x] No 30
 * [x] No 31
 * [x] No 32
 * [x] No 33
 * [x] No 34
 * [x] No 35
 * [x] No 36
 * [x] No 37
 * [x] No 38
 * [x] No 39 (A and B - need two flyers)
 * [x] No 40
 * [x] No 41
 * [x] No 42
 * [x] No 43
 * [x] No 44
 * [x] No 45
 * [x] No 46
 * [x] No 47
 * (No 48)
 * [x] No 49
 * No 50 - Mr Fluffy, demolished
 * [x] No 51 - needs 2 flyers

**Comment by monkeypants** [comment]
after these, we need to do Welsh place too. And then we need to put the pictures in DropBox or something, and then use them to make flyers.

**Comment by monkeypants** [comment]
Welsh street has these numbers:
 * [x] No 1
 * (No 2)
 * [x] No 3
 * [x] No 4
 * [x] No 5
 * [x] No 6
 * [x] No 7
 * [x] No 8
 * [x] No 9
 * [x] No 10

**Comment by monkeypants** [comment]
I'm uploading the raw photos here https://www.dropbox.com/home/pocketmoneyindustries

**Comment by yaya-galah** [comment]
I have done that.  #18

**Comment by monkeypants** [comment]
@yaya-galah can you see the images in the link above (dropbox) ? I think I set up permissions for you but am not sure I got it right. Let me know if you can't get in.

Right now, I'm renaming the images into street number. When that's done, and you can access them, then I think this ticket can close.

**Comment by monkeypants** [comment]
did you try the link? can you see the images?
